logging:
  level: INFO
  loggers:
    com.mapt: DEBUG
template: Hello, %s!
defaultName: Stranger
assets:
  mappings:
    /assets: /
  overrides:
    /: /mapt/build
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/maptdb?autoReconnect=true&useSSL=false&serverTimezone=UTC
  user: root
  password: beamerBoi
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
